curl -X POST localhost:8081/commandElections -H "Content-Type:Application/json" -d {\"command\":\"start\"}


curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":1,\"party\":\"Republicans\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":1,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":1,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":1,\"party\":\"Democrats\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":1,\"party\":\"Republicans\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":1,\"party\":\"Democrats\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":1,\"party\":\"Republicans\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":1,\"party\":\"Democrats\"}
curl -X POST localhost:8087/votes -H "Content-Type:Application/json" -d {\"clientId\":1,\"party\":\"Republicans\"}
curl -X POST localhost:8087/votes -H "Content-Type:Application/json" -d {\"clientId\":1,\"party\":\"Democrats\"}
curl -X POST localhost:8087/votes -H "Content-Type:Application/json" -d {\"clientId\":1,\"party\":\"Republicans\"}
curl -X POST localhost:8087/votes -H "Content-Type:Application/json" -d {\"clientId\":1,\"party\":\"Democrats\"}
curl -X POST localhost:8087/votes -H "Content-Type:Application/json" -d {\"clientId\":1,\"party\":\"Republicans\"}
curl -X POST localhost:8087/votes -H "Content-Type:Application/json" -d {\"clientId\":1,\"party\":\"Democrats\"}
curl -X POST localhost:8087/votes -H "Content-Type:Application/json" -d {\"clientId\":1,\"party\":\"Republicans\"}
curl -X POST localhost:8087/votes -H "Content-Type:Application/json" -d {\"clientId\":1,\"party\":\"Democrats\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":1,\"party\":\"Republicans\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":1,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":1,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":1,\"party\":\"Democrats\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":1,\"party\":\"Republicans\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":1,\"party\":\"Democrats\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":1,\"party\":\"Republicans\"}
curl -X POST localhost:8087/votes -H "Content-Type:Application/json" -d {\"clientId\":1,\"party\":\"Democrats\"}
curl -X POST localhost:8087/votes -H "Content-Type:Application/json" -d {\"clientId\":1,\"party\":\"Republicans\"}
curl -X POST localhost:8087/votes -H "Content-Type:Application/json" -d {\"clientId\":1,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":1,\"party\":\"Republicans\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":1,\"party\":\"Democrats\"}
curl -X POST localhost:8087/votes -H "Content-Type:Application/json" -d {\"clientId\":1,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":1,\"party\":\"Democrats\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":1,\"party\":\"Republicans\"}
curl -X POST localhost:8087/votes -H "Content-Type:Application/json" -d {\"clientId\":1,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":1,\"party\":\"Republicans\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":1,\"party\":\"Democrats\"}
curl -X POST localhost:8087/votes -H "Content-Type:Application/json" -d {\"clientId\":1,\"party\":\"Republicans\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":1,\"party\":\"Democrats\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":1,\"party\":\"Republicans\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":1,\"party\":\"Democrats\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":1,\"party\":\"Republicans\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":1,\"party\":\"Democrats\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":1,\"party\":\"Republicans\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":1,\"party\":\"Democrats\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":1,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":1,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":1,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":1,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":1,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":1,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":1,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":1,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":1,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":1,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":1,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":1,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":1,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":1,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":1,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":1,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":1,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":1,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":1,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":1,\"party\":\"Democrats\"}
curl -X POST localhost:8087/votes -H "Content-Type:Application/json" -d {\"clientId\":1,\"party\":\"Republicans\"}
curl -X POST localhost:8087/votes -H "Content-Type:Application/json" -d {\"clientId\":1,\"party\":\"Democrats\"}


curl -X POST localhost:8087/votes -H "Content-Type:Application/json" -d {\"clientId\":33,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":33,\"party\":\"Republicans\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":33,\"party\":\"Democrats\"}
curl -X POST localhost:8087/votes -H "Content-Type:Application/json" -d {\"clientId\":33,\"party\":\"Republicans\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":33,\"party\":\"Democrats\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":33,\"party\":\"Republicans\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":33,\"party\":\"Democrats\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":33,\"party\":\"Republicans\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":33,\"party\":\"Democrats\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":33,\"party\":\"Republicans\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":33,\"party\":\"Democrats\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":33,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":33,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":33,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":33,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":33,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":33,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":33,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":33,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":33,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":33,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":33,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":33,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":33,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":33,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":33,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":33,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":33,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":33,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":33,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":33,\"party\":\"Democrats\"}
curl -X POST localhost:8087/votes -H "Content-Type:Application/json" -d {\"clientId\":33,\"party\":\"Republicans\"}
curl -X POST localhost:8087/votes -H "Content-Type:Application/json" -d {\"clientId\":33,\"party\":\"Democrats\"}

curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":44,\"party\":\"Republicans\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":44,\"party\":\"Democrats\"}
curl -X POST localhost:8087/votes -H "Content-Type:Application/json" -d {\"clientId\":44,\"party\":\"Republicans\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":44,\"party\":\"Democrats\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":44,\"party\":\"Republicans\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":44,\"party\":\"Democrats\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":44,\"party\":\"Republicans\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":44,\"party\":\"Democrats\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":44,\"party\":\"Republicans\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":44,\"party\":\"Democrats\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":44,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":44,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":44,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":44,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":44,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":44,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":44,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":44,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":44,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":44,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":44,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":44,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":44,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":44,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":44,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":44,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":44,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":44,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":44,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":44,\"party\":\"Democrats\"}
curl -X POST localhost:8087/votes -H "Content-Type:Application/json" -d {\"clientId\":44,\"party\":\"Republicans\"}
curl -X POST localhost:8087/votes -H "Content-Type:Application/json" -d {\"clientId\":44,\"party\":\"Democrats\"}


curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":55,\"party\":\"Republicans\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":55,\"party\":\"Democrats\"}
curl -X POST localhost:8087/votes -H "Content-Type:Application/json" -d {\"clientId\":55,\"party\":\"Republicans\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":55,\"party\":\"Democrats\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":55,\"party\":\"Republicans\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":55,\"party\":\"Democrats\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":55,\"party\":\"Republicans\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":55,\"party\":\"Democrats\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":55,\"party\":\"Republicans\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":55,\"party\":\"Democrats\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":55,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":55,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":55,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":55,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":55,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":55,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":55,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":55,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":55,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":55,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":55,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":55,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":55,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":55,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":55,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":55,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":55,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":55,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":55,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":55,\"party\":\"Democrats\"}
curl -X POST localhost:8087/votes -H "Content-Type:Application/json" -d {\"clientId\":55,\"party\":\"Republicans\"}
curl -X POST localhost:8087/votes -H "Content-Type:Application/json" -d {\"clientId\":55,\"party\":\"Democrats\"}

curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":66,\"party\":\"Republicans\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":66,\"party\":\"Democrats\"}
curl -X POST localhost:8087/votes -H "Content-Type:Application/json" -d {\"clientId\":66,\"party\":\"Republicans\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":66,\"party\":\"Democrats\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":66,\"party\":\"Republicans\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":66,\"party\":\"Democrats\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":66,\"party\":\"Republicans\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":66,\"party\":\"Democrats\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":66,\"party\":\"Republicans\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":66,\"party\":\"Democrats\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":66,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":66,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":66,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":66,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":66,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":66,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":66,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":66,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":66,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":66,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":66,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":66,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":66,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":66,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":66,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":66,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":66,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":66,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":66,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":66,\"party\":\"Democrats\"}
curl -X POST localhost:8087/votes -H "Content-Type:Application/json" -d {\"clientId\":66,\"party\":\"Republicans\"}
curl -X POST localhost:8087/votes -H "Content-Type:Application/json" -d {\"clientId\":66,\"party\":\"Democrats\"}

curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":77,\"party\":\"Republicans\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":77,\"party\":\"Democrats\"}
curl -X POST localhost:8087/votes -H "Content-Type:Application/json" -d {\"clientId\":77,\"party\":\"Republicans\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":77,\"party\":\"Democrats\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":77,\"party\":\"Republicans\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":77,\"party\":\"Democrats\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":77,\"party\":\"Republicans\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":77,\"party\":\"Democrats\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":77,\"party\":\"Republicans\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":77,\"party\":\"Democrats\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":77,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":77,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":77,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":77,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":77,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":77,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":77,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":77,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":77,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":77,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":77,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":77,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":77,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":77,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":77,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":77,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":77,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":77,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":77,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":77,\"party\":\"Democrats\"}
curl -X POST localhost:8087/votes -H "Content-Type:Application/json" -d {\"clientId\":77,\"party\":\"Republicans\"}
curl -X POST localhost:8087/votes -H "Content-Type:Application/json" -d {\"clientId\":77,\"party\":\"Democrats\"}


curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":88,\"party\":\"Republicans\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":88,\"party\":\"Democrats\"}
curl -X POST localhost:8087/votes -H "Content-Type:Application/json" -d {\"clientId\":88,\"party\":\"Republicans\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":88,\"party\":\"Democrats\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":88,\"party\":\"Republicans\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":88,\"party\":\"Democrats\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":88,\"party\":\"Republicans\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":88,\"party\":\"Democrats\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":88,\"party\":\"Republicans\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":88,\"party\":\"Democrats\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":88,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":88,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":88,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":88,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":88,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":88,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":88,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":88,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":88,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":88,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":88,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":88,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":88,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":88,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":88,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":88,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":88,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":88,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":88,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":88,\"party\":\"Democrats\"}
curl -X POST localhost:8087/votes -H "Content-Type:Application/json" -d {\"clientId\":88,\"party\":\"Republicans\"}
curl -X POST localhost:8087/votes -H "Content-Type:Application/json" -d {\"clientId\":88,\"party\":\"Democrats\"}


curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":99,\"party\":\"Republicans\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":99,\"party\":\"Democrats\"}
curl -X POST localhost:8087/votes -H "Content-Type:Application/json" -d {\"clientId\":99,\"party\":\"Republicans\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":99,\"party\":\"Democrats\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":99,\"party\":\"Republicans\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":99,\"party\":\"Democrats\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":99,\"party\":\"Republicans\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":99,\"party\":\"Democrats\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":99,\"party\":\"Republicans\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":99,\"party\":\"Democrats\"}
curl -X POST localhost:8084/votes -H "Content-Type:Application/json" -d {\"clientId\":99,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":99,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":99,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":99,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":99,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":99,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":99,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":99,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":99,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":99,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":99,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":99,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":99,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":99,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":99,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":99,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":99,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":99,\"party\":\"Democrats\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":99,\"party\":\"Republicans\"}
curl -X POST localhost:8081/votes -H "Content-Type:Application/json" -d {\"clientId\":99,\"party\":\"Democrats\"}
curl -X POST localhost:8087/votes -H "Content-Type:Application/json" -d {\"clientId\":99,\"party\":\"Republicans\"}
curl -X POST localhost:8087/votes -H "Content-Type:Application/json" -d {\"clientId\":99,\"party\":\"Democrats\"}

curl -X POST localhost:8081/commandElections -H "Content-Type:Application/json" -d {\"command\":\"end\"}